import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useI18n } from '@/i18n';
import { useDeviceList, useSyncMeta } from '@/sync/useSyncState';
import { checkIdentity, connectSync, disconnectSync } from '@/sync/engine';
import { buildJoinLink, parseJoinLinkParams } from '@/sync/identity';
import { shortDeviceId } from '@/sync/deviceId';
import { renderQrSvg } from '@/sync/qr';

type FormError = 'sync.nameRequired' | 'sync.nameIncomplete' | 'sync.dobRequired' | 'sync.dobFuture' | 'sync.linkError' | 'sync.joinNotFound';

/** A name needs at least 2 space-separated words (first + last) — a shallow,
 * frontend-only sanity check. There's no way to actually verify a real name. */
export function hasFullName(name: string): boolean {
  return name.trim().split(/\s+/).filter(Boolean).length >= 2;
}

export function SyncPage() {
  const { t, lang } = useI18n();
  const meta = useSyncMeta();
  const devices = useDeviceList();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [busy, setBusy] = useState(false);
  const [nameInput, setNameInput] = useState('');
  const [dobInput, setDobInput] = useState('');
  const [formError, setFormError] = useState<FormError | null>(null);
  // Set once a checked identity comes back with no existing data: holds off
  // creating anything until the user explicitly confirms via "Registrar",
  // so a typo doesn't silently spawn a new account. Cleared whenever the
  // fields are edited again, so a stale confirmation can't fire on new input.
  const [pendingRegister, setPendingRegister] = useState<{ name: string; dob: string } | null>(null);
  const [copied, setCopied] = useState(false);

  const editName = (v: string) => {
    setNameInput(v);
    setPendingRegister(null);
  };
  const editDob = (v: string) => {
    setDobInput(v);
    setPendingRegister(null);
  };

  // Scanning the QR (or opening a shared sync link) lands here as
  // /sync/join?name=...&dob=... — prefill and connect immediately, same
  // one-step "instantly synced" directness as before, but only when the
  // identity actually exists: a QR is only ever generated by an *already
  // synced* device, so failing to find it here is a real error (a stale
  // scan, a network hiccup) rather than an invitation to register — the
  // user is told to retry the scan instead. Guarded against StrictMode's
  // double-invoke and against clobbering a device that's already syncing
  // under a different identity (that needs an explicit disconnect first,
  // not a silent switch).
  const attempted = useRef(false);
  useEffect(() => {
    const joinParams = parseJoinLinkParams(searchParams);
    if (!joinParams || meta.enabled || attempted.current) {
      if (joinParams && meta.enabled) navigate('/sync', { replace: true });
      return;
    }
    attempted.current = true;
    setNameInput(joinParams.name);
    setDobInput(joinParams.dob);
    setBusy(true);
    setFormError(null);
    void (async () => {
      const check = await checkIdentity(joinParams);
      if (!check.ok) {
        setFormError('sync.linkError');
      } else if (!check.exists) {
        setFormError('sync.joinNotFound');
      } else {
        const result = await connectSync(joinParams);
        if (!result.ok) setFormError('sync.linkError');
      }
      setBusy(false);
      navigate('/sync', { replace: true });
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams, meta.enabled]);

  const linkUrl = meta.name && meta.dob ? buildJoinLink({ name: meta.name, dob: meta.dob }) : '';
  const qrSvg = useMemo(() => (linkUrl ? renderQrSvg(linkUrl) : ''), [linkUrl]);

  const handleConnect = async () => {
    const name = nameInput.trim();
    const dob = dobInput.trim();
    if (!name) return setFormError('sync.nameRequired');
    if (!hasFullName(name)) return setFormError('sync.nameIncomplete');
    if (!dob) return setFormError('sync.dobRequired');
    if (new Date(dob).getTime() > Date.now()) return setFormError('sync.dobFuture');

    setBusy(true);
    setFormError(null);
    try {
      const check = await checkIdentity({ name, dob });
      if (!check.ok) {
        setFormError('sync.linkError');
      } else if (check.exists) {
        const result = await connectSync({ name, dob });
        if (!result.ok) setFormError('sync.linkError');
      } else {
        // No data under this identity — hold off creating it until the
        // user confirms with "Registrar" (handleRegister below).
        setPendingRegister({ name, dob });
      }
    } finally {
      setBusy(false);
    }
  };

  const handleRegister = async () => {
    if (!pendingRegister) return;
    setBusy(true);
    setFormError(null);
    try {
      const result = await connectSync(pendingRegister);
      if (!result.ok) setFormError('sync.linkError');
      else setPendingRegister(null);
    } finally {
      setBusy(false);
    }
  };

  const handleCopy = () => {
    void navigator.clipboard.writeText(linkUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handleDisconnect = () => {
    if (confirm(t('sync.disconnectConfirm'))) disconnectSync();
  };

  const dateFmt = (when: string | number) => new Date(when).toLocaleString(lang === 'es' ? 'es-AR' : 'en-US', { dateStyle: 'short', timeStyle: 'short' });

  return (
    <div className="stats sync">
      <h1>{t('sync.title')}</h1>

      {!meta.enabled && (
        <section className="stats__block">
          <p>{t('sync.disabledIntro')}</p>
          <div className="sync__form">
            <label className="sync__field">
              {t('sync.nameLabel')}
              <input
                type="text"
                className="sync__input"
                value={nameInput}
                onChange={(e) => editName(e.target.value)}
                placeholder={t('sync.namePlaceholder')}
              />
            </label>
            <label className="sync__field">
              {t('sync.dobLabel')}
              <input type="date" className="sync__input" value={dobInput} onChange={(e) => editDob(e.target.value)} />
            </label>
            <button className="btn btn--primary" onClick={() => void handleConnect()} disabled={busy || !!pendingRegister}>
              {busy && !pendingRegister ? t('sync.connecting') : t('sync.connect')}
            </button>
            {pendingRegister && (
              <>
                <p className="sync__notice">{t('sync.registerPrompt')}</p>
                <button className="btn btn--accent" onClick={() => void handleRegister()} disabled={busy}>
                  {busy ? t('sync.registering') : t('sync.register')}
                </button>
              </>
            )}
          </div>
          {formError && <p className="sync__error">{t(formError)}</p>}
        </section>
      )}

      {meta.enabled && meta.secretHash && (
        <section className="stats__block sync__code-block">
          <h2>
            {t('sync.syncedAs')}: {meta.name}
          </h2>
          <div className="settings__row">
            <button className="btn btn--ghost" onClick={handleCopy}>
              {copied ? t('sync.copied') : t('sync.copy')}
            </button>
          </div>
          <div className="sync__qr" dangerouslySetInnerHTML={{ __html: qrSvg }} />
          <p className="muted">{t('sync.scanHint')}</p>
          <p className="muted">
            {t('sync.lastSynced')}: {meta.lastSyncedAt ? dateFmt(meta.lastSyncedAt) : t('sync.never')}
          </p>
          <button className="btn btn--danger" onClick={handleDisconnect}>
            {t('sync.disconnect')}
          </button>
        </section>
      )}

      {meta.enabled && (
        <section className="stats__block">
          <h2>{t('sync.devices')}</h2>
          <table className="sessions">
            <thead>
              <tr>
                <th>{t('stats.deviceId')}</th>
                <th>{t('stats.device')}</th>
                <th>{t('sync.lastSynced')}</th>
              </tr>
            </thead>
            <tbody>
              {devices.map((d) => (
                <tr key={d.deviceId}>
                  <td>{shortDeviceId(d.deviceId)}</td>
                  <td>
                    {d.label}
                    {d.isSelf && <span className="tag">{t('sync.thisDevice')}</span>}
                  </td>
                  <td>{d.lastActiveAt ? dateFmt(d.lastActiveAt) : t('sync.never')}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}
    </div>
  );
}
