/**
 * Level layouts, ported verbatim from the real Amblyonoid source (FUENTES/ark,
 * src/levels.ts). Each row is a string of 2-char codes decoded by CODE_HITS:
 * 'xx' = indestructible, '  ' = empty, 'aa'..'dd' = 1..4 hits needed.
 */
export const CODE_HITS: Record<string, number> = {
  xx: -1,
  '  ': 0,
  aa: 1,
  bb: 2,
  cc: 3,
  dd: 4,
};

export const LEVELS: string[][] = [
  [
    '                  ',
    '                  ',
    '                  ',
    '                  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
  ],
  [
    '                  ',
    '                  ',
    '                  ',
    '  bbbbbbbbbbbbbb  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
    '  bbbbbbbbbbbbbb  ',
  ],
  [
    '                  ',
    '                  ',
    '  aaccaaccaaccaa  ',
    '  aaaaccaaccaaaa  ',
    '                  ',
    '  aaaaccaaccaaaa  ',
    '  aaccaaccaaccaa  ',
  ],
  [
    '                  ',
    '                  ',
    '    cccccccccc    ',
    '      bbbbbb      ',
    '        aa        ',
    '        aa        ',
    '      bbbbbb      ',
    '    cccccccccc    ',
  ],
  [
    '                  ',
    '                  ',
    '  bbbbbb  bbbbbb  ',
    '  aaaaaa  aaaaaa  ',
    '  aaaaaa  aaaaaa  ',
    '                  ',
    '                  ',
    '      xxxxxx      ',
  ],
  [
    '                  ',
    '                  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
    '                  ',
    '                  ',
    '  xx    xx    xx  ',
  ],
  [
    '                  ',
    '                  ',
    '  bbbbbbbbbbbbbb  ',
    '  aaaaaaaaaaaaaa  ',
    '  aaaaaaaaaaaaaa  ',
    '                  ',
    '                  ',
    '  xxxx      xxxx  ',
  ],
  [
    '                  ',
    '                  ',
    '    aa      aa    ',
    '  aabbaa  aabbaa  ',
    '  aabbaa  aabbaa  ',
    '    aa      aa    ',
    '                  ',
    '                  ',
    '    xx      xx    ',
    '      xxxxxx      ',
  ],
  [
    '                  ',
    '                  ',
    '    bb      bb    ',
    '  bbddbb  bbddbb  ',
    '  bbddbb  bbddbb  ',
    '    bb      bb    ',
    '                  ',
    '                  ',
    '      xxxxxx      ',
    '    xx      xx    ',
  ],
  [
    '    bb      bb    ',
    '      bb  bb      ',
    '    aaaaaaaaaa    ',
    '  aaaabbaabbaaaa  ',
    '  aaaabbaabbaaaa  ',
    'aaaaaaaaaaaaaaaaaa',
    'aa  aaaaaaaaaa  aa',
    'aa  aa      aa  aa',
    '      aa  aa      ',
    '      aa  aa      ',
  ],
  [
    '                  ',
    '  bbbbbbbbbbbbbb  ',
    '  bb          bb  ',
    '  bb    dd    bb  ',
    '  bb  dddddd  bb  ',
    '  bb  dddddd  bb  ',
    '  bb    dd    bb  ',
    '  bb          bb  ',
    '  bbbbbbbbbbbbbb  ',
  ],
  [
    '                  ',
    '  bbbbbbbbbbbbbb  ',
    '  bbbbbbbbbbbbbb  ',
    '                  ',
    '        aa        ',
    '      aaaaaa      ',
    '        aa        ',
    '                  ',
    '  bbbbbbbbbbbbbb  ',
    '  bbbbbbbbbbbbbb  ',
  ],
  [
    '                  ',
    '        aa        ',
    '      aa  aa      ',
    'aaaaaaaaaaaaaaaaaa',
    '  aa  aa  aa  aa  ',
    '    aa      aa    ',
    '    aa      aa    ',
    '  aa  aa  aa  aa  ',
    'aaaaaaaaaaaaaaaaaa',
    '      aa  aa      ',
    '        aa        ',
  ],
  [
    'dd                ',
    'dddd              ',
    'cccccc            ',
    'cccccccc          ',
    'bbbbbbbbbb        ',
    'bbbbbbbbbbbb      ',
    'aaaaaaaaaaaaaa    ',
    'aaaaaaaaaaaaaaaa  ',
    'aaaaaaaaaaaaaaaaaa',
  ],
];
